### ISSUE TITLE
10 frames repaire need 10min in 854 x 480 on A800?

### ISSUE THREAD

**Issue by zdyshine** [jimmycv07/DiffIR2VR-Zero#1]
10 frames repaire need 10min in 854 x 480 on A800?
Is this time reasonable？

**Comment by gvonkreisler** [comment]
Thank you for your work?
Flawless installation  !!!
But as zdyshine mentioned: It takes a lot of time with iteration 50.

Could their a way to make it faster?
Cheers george

**Comment by Oguzhanercan** [comment]
how much vram required?

**Comment by jimmycv07** [comment]
Thank you all for your interest in our work. We tested our method on a 4090 Ti, and it roughly requires 3 minutes and 13GB of GPU memory for 10 frames with a size of 512 x 960. For faster inference, you could try reducing the denoising timesteps by running the script with `--steps t`. We are also working on optimizing efficiency and will provide updates once we improve the speed.

**Comment by zdyshine** [comment]
![image](https://github.com/jimmycv07/DiffIR2VR-Zero/assets/35593072/5ccdad4b-22c7-4573-a0bf-1003177db102)
10 frames repaire  with 854 x 480 on A800

**Comment by gvonkreisler** [comment]
I repair a black and white video and the results are very good !
Most of  the scratches  are gone. Better result than every other github project.
I tested them all.
I choose only 2 iteration (steps) for the clips. (not 50).

This is a change for conservation the film heritage, and also for you to do a commercial product for repairing old films.

Thank you again
George

**Comment by jimmycv07** [comment]
@gvonkreisler  Hi George, thank you so much for sharing your success and for your kind words. I'm glad to hear that our work has been helpful to you !!

Changhan
